### ISSUE TITLE
Forza Horizon 5 issue with gamepass

### ISSUE THREAD

**Issue by gandazx** [Paliverse/DualSenseX#57] opened 2021-11-16 16:50 UTC
the game just not recognises the  xbox controller emulation, it keeps saying to reconnect the controller, it started to happened after the version 1.4.5, I'm using usb method by the way

**Comment by Paliverse** [comment] 2021-11-16 22:10
Are you playing on steam or Xbox store? you should try to connect to the app first, make sure emulation is Xbox 360 and then launch the game, if still issues, let me know

**Comment by gandazx** [comment] 2021-11-16 22:29
xbox store, i already tried do that, but it keeps glitching, so i downgraded to the 1.4.4 version and it worked again

**Comment by Paliverse** [comment] 2021-11-16 22:57
Hmm that’s odd, I’ve just tried it with Bluetooth connection and it works, but I’m getting the same issue with you through USB. Can you try other games? If it’s working with other games, the issue might be with Forza

**Comment by gandazx** [comment] 2021-11-16 23:15
ok, I will try with forza 4, it will be helpful?

**Comment by gandazx** [comment] 2021-11-16 23:17
I’m using usb connection because my pc doesn’t have a bluetooth dongle, I need to buy one

**Comment by Inferno011** [comment] 2021-11-17 01:06
> 
> 
> Hmm that’s odd, I’ve just tried it with Bluetooth connection and it works, but I’m getting the same issue as you through USB. Can you try other games? If it’s working with other games, the issue might be with Forza

 I have the exact same issue as him on Forza 5 it only happens when plugged in if it's by Bluetooth it's fine older versions also worked for me.

**Comment by Slickrick1121** [comment] 2021-11-17 04:28
> 
> 
> Hmm that’s odd, I’ve just tried it with Bluetooth connection and it works, but I’m getting the same issue as you through USB. Can you try other games? If it’s working with other games, the issue might be with Forza

yep yep, having this issue as well. Just did a rollback and all good now.

**Comment by Slickrick1121** [comment] 2021-11-17 04:29
> 
> 
> xbox store, i already tried do that, but it keeps glitching, so i downgraded to the 1.4.4 version and it worked again

Thanks that fixed it for me

**Comment by Paliverse** [comment] 2021-11-21 13:36
Currently I’m away out of town, once I come back im gonna get to the bottom of it and get it fixed. Probably some dumb mistake I did that I haven’t noticed, beauty of programming

**Comment by Paliverse** [comment] 2021-11-26 19:40
After a lot of testing, it seems the issue is from Forza itself

**Comment by Slickrick1121** [comment] 2021-11-26 19:54
> After a lot of testing, it seems the issue is from Forza itself

thanks for the investigation. Yeah I saw a lot of people complaining about it using other software as well.

**Comment by Paliverse** [comment] 2021-11-27 21:57
I have found a good fix for this issue, currently uploading video on youtube, once it's ready, ill share the link :)

**Comment by Paliverse** [comment] 2021-11-27 23:36
Video is now live on YouTube, here's the Fix: https://www.youtube.com/watch?v=1LfwmiRUMTU

**Comment by TRILXGY** [comment] 2022-01-04 15:54
I have never had a issue until the new update of 1.4.9 the forza issue where it prioritizes the keyboard is back , and hidhide does not seem to be on the settings. is there a way i can downgrade update?

**Closed** 2022-01-22 05:04 UTC
